### PR TITLE
Add mac target

### PR DESCRIPTION
**Pull request by edwardaux**
Hi... I've been working on a Mac app that uses LivioHTTPServer, which obviously has SuperSocket as a dependency.

This PR contains the changes I made to get it build as a Mac target. Once (if?) you are happy with this, I will submit a similar PR for LivioHTTPServer.

Let me know if you have any questions or concerns.

### CODE REVIEW

**Comment by joeljfischer** [comment]
Hey @edwardaux, thanks for the PR! Sorry to come back to it 3 weeks later, I promise it was open in a tab the whole time. Looks good, but I do have a few points:
1. It looks like the original SuperSocket scheme can go away
2. It looks like there is a group with duplicate references to the SuperSocket.h file and Info.plist, but when I tried to remove them, I got a warning saying that no umbrella header was found for the Mac target.
3. It appears I'm missing the platform and versions supported in the podspec, could you add those for Mac & iOS?
4. It appears that the mac target build phase is missing project headers.

Thanks!

**Comment by edwardaux** [comment]
he he... I know the feeling, I also have two PRs for one of my projects sitting in tabs waiting for me to get time to review :blush:  

Thansk for the feedback... I'll have a look today and address them shortly.

**Comment by edwardaux** [comment]
_1. SuperSocket scheme_ 
I think this is an artefact of the fact that `.gitignore` (both on this project, and also in most people's global settings) says to ignore `xcuserdata`.  I suspect that if you look at your `SuperSocket.xcodeproj/xcuserdata/xxx.xcuserdatad/xcschemes` directory, you will see a residual file called something like `SuperSocket.xcscheme`.  My directory structure is show below:

screen shot 2015-11-21 at 8 57 10 am

You should just be able to delete that file. Given that `xcuserdata` is ignored by git, this is a tricky one to resolve.

**Comment by edwardaux** [comment]
_2. Duplicate SuperSocket group_
Oops... sorry. Removed duplicate references.

**Comment by edwardaux** [comment]
_3. Podspec support_
Added (sorry... I'm a carthage user and forgot to check for a pod spec)

**Comment by edwardaux** [comment]
_4. Umbrella header error_
Fixed.

**Comment by joeljfischer** [comment]
For number 4, if you go to the SuperSocket iOS target build phase, you'll see that it has 11 headers, 5 public, 6 project. The SuperSocket Mac target build phase for headers has only the 5 public headers.

**Comment by edwardaux** [comment]
@joeljfischer I've just changed the Mac target to add the same headers to Project scope. Although, it actually doesn't make any difference... I could just have easily removed them the Project scope in the iOS target - I just figured it'd be lower risk if I made as few changes to the iOS target as possible. Hope that's OK.

**Comment by joeljfischer** [comment]
Yup, that's what I was looking for! Thanks.

**Pull request merged**
